[package]
name = "pc"
version = "0.1.0"
edition = "2021"

[dependencies]
libui = { path = "../libui" }
pixels = "0.13.0"
winit = { version = "0.29", default-features = false, features = ["rwh_05", "x11", "wayland"] }
winit_input_helper = "0.15"